-- Glossary audit: dismiss the differences where the NEW site already
-- follows the January 2026 word list and production does not.
--
-- Generated by .scratch/glossary-audit/emit.py. Re-runnable: each row is
-- guarded on overrides_current, so a finding an editor has already decided
-- is left alone and a second run writes nothing.
--
-- 22 findings. Every one is a case/punctuation-only difference
-- on a short label, verified word-identical apart from case and the (R) mark.

begin;

-- be/carport/productinformatie  [casing]
--   prod: Gumax® Glazen schuifwand
--   new : Gumax® glazen schuifwand
insert into overrides (editor, scope, action, store, page, finding_id, note)
select 'glossary-audit', 'finding', 'dismissed', 'be', 'carport/productinformatie', 't4F0I4QFR4Fp73KF', 'Woordenlijst jan-2026: nieuwe site volgt de lijst (Gumax® glazen schuifwand); productie niet.'
where not exists (
  select 1 from overrides_current c
  where c.scope = 'finding' and c.finding_id = 't4F0I4QFR4Fp73KF'
    and c.action in ('dismissed', 'fixed')
);

-- be/carport/productinformatie  [casing]
--   prod: Gumax® Steel look glazen schuifwand
--   new : Gumax® Steel Look glazen schuifwand
insert into overrides (editor, scope, action, store, page, finding_id, note)
select 'glossary-audit', 'finding', 'dismissed', 'be', 'carport/productinformatie', 'xdnbtJ6oyHbX_Q9J', 'Woordenlijst jan-2026: nieuwe site volgt de lijst (Gumax® Steel Look glazen schuifwand); productie niet.'
where not exists (
  select 1 from overrides_current c
  where c.scope = 'finding' and c.finding_id = 'xdnbtJ6oyHbX_Q9J'
    and c.action in ('dismissed', 'fixed')
);

-- be/carport/productinformatie  [casing]
--   prod: Gumax® Shading panel
--   new : Gumax® Shading Panel
insert into overrides (editor, scope, action, store, page, finding_id, note)
select 'glossary-audit', 'finding', 'dismissed', 'be', 'carport/productinformatie', '93h804NS2cN0jI0A', 'Woordenlijst jan-2026: nieuwe site volgt de lijst (Gumax® Shading Panel(s)); productie niet.'
where not exists (
  select 1 from overrides_current c
  where c.scope = 'finding' and c.finding_id = '93h804NS2cN0jI0A'
    and c.action in ('dismissed', 'fixed')
);

-- be/glazen-schuifwand/productinformatie  [casing]
--   prod: Gumax® Deurmeenemers
--   new : Gumax® deurmeenemers
insert into overrides (editor, scope, action, store, page, finding_id, note)
select 'glossary-audit', 'finding', 'dismissed', 'be', 'glazen-schuifwand/productinformatie', 't2WqGGus3R7ccOnj', 'Woordenlijst jan-2026: nieuwe site volgt de lijst (Gumax® deurmeenemer); productie niet.'
where not exists (
  select 1 from overrides_current c
  where c.scope = 'finding' and c.finding_id = 't2WqGGus3R7ccOnj'
    and c.action in ('dismissed', 'fixed')
);

-- be/schuifwand  [casing]
--   prod: Gumax® Schuifwanden voor uw overkapping
--   new : Gumax® schuifwanden voor uw overkapping
insert into overrides (editor, scope, action, store, page, finding_id, note)
select 'glossary-audit', 'finding', 'dismissed', 'be', 'schuifwand', 'yQCx5UDPorlYNWn2', 'Woordenlijst jan-2026: nieuwe site volgt de lijst (Gumax® schuifwand(en)); productie niet.'
where not exists (
  select 1 from overrides_current c
  where c.scope = 'finding' and c.finding_id = 'yQCx5UDPorlYNWn2'
    and c.action in ('dismissed', 'fixed')
);

-- be/schuifwand  [casing]
--   prod: Gumax® Hor schuifdeur
--   new : Gumax® hor schuifdeur
insert into overrides (editor, scope, action, store, page, finding_id, note)
select 'glossary-audit', 'finding', 'dismissed', 'be', 'schuifwand', 'TzKl6RKMHF7UugNy', 'Woordenlijst jan-2026: nieuwe site volgt de lijst (Gumax® hor schuifdeur); productie niet.'
where not exists (
  select 1 from overrides_current c
  where c.scope = 'finding' and c.finding_id = 'TzKl6RKMHF7UugNy'
    and c.action in ('dismissed', 'fixed')
);

-- be/voordelen-van-een-aluminium-terrasoverkapping  [casing]
--   prod: Modern, klassiek, Tijdloos, Authentiek of Eigentijds ontwerp
--   new : Modern, Klassiek, Tijdloos, Authentiek of Eigentijds ontwerp
insert into overrides (editor, scope, action, store, page, finding_id, note)
select 'glossary-audit', 'finding', 'dismissed', 'be', 'voordelen-van-een-aluminium-terrasoverkapping', '0nRkvFDiwzSZuJzn', 'Woordenlijst jan-2026: nieuwe site volgt de lijst (Klassiek); productie niet.'
where not exists (
  select 1 from overrides_current c
  where c.scope = 'finding' and c.finding_id = '0nRkvFDiwzSZuJzn'
    and c.action in ('dismissed', 'fixed')
);

-- be/zwarte-overkapping  [casing]
--   prod: Stijlvol & tijdloos
--   new : Stijlvol & Tijdloos
insert into overrides (editor, scope, action, store, page, finding_id, note)
select 'glossary-audit', 'finding', 'dismissed', 'be', 'zwarte-overkapping', 'bLWGsjOFZktIAWkD', 'Woordenlijst jan-2026: nieuwe site volgt de lijst (Tijdloos); productie niet.'
where not exists (
  select 1 from overrides_current c
  where c.scope = 'finding' and c.finding_id = 'bLWGsjOFZktIAWkD'
    and c.action in ('dismissed', 'fixed')
);

-- be/zwarte-overkapping  [casing]
--   prod: glazen schuifwanden
--   new : Glazen schuifwanden
insert into overrides (editor, scope, action, store, page, finding_id, note)
select 'glossary-audit', 'finding', 'dismissed', 'be', 'zwarte-overkapping', 'UwPZx3nnmYkJxSOx', 'Woordenlijst jan-2026: nieuwe site volgt de lijst (Glazen schuifwand); productie niet.'
where not exists (
  select 1 from overrides_current c
  where c.scope = 'finding' and c.finding_id = 'UwPZx3nnmYkJxSOx'
    and c.action in ('dismissed', 'fixed')
);

-- be_fr/verlichting  [copy]
--   prod: Choisissez vos spots LED >
--   new : Choisissez vos Spots LED
insert into overrides (editor, scope, action, store, page, finding_id, note)
select 'glossary-audit', 'finding', 'dismissed', 'be_fr', 'verlichting', 'ZRGgNdpU40IznWhR', 'Woordenlijst jan-2026: nieuwe site volgt de lijst (Spots LED); productie niet.'
where not exists (
  select 1 from overrides_current c
  where c.scope = 'finding' and c.finding_id = 'ZRGgNdpU40IznWhR'
    and c.action in ('dismissed', 'fixed')
);

-- de/downloads  [casing]
--   prod: Das installationsvideo ansehen
--   new : Das Installationsvideo ansehen
insert into overrides (editor, scope, action, store, page, finding_id, note)
select 'glossary-audit', 'finding', 'dismissed', 'de', 'downloads', 'WtoGwnvsezYzoBtI', 'Woordenlijst jan-2026: nieuwe site volgt de lijst (Installationsvideo(s)); productie niet.'
where not exists (
  select 1 from overrides_current c
  where c.scope = 'finding' and c.finding_id = 'WtoGwnvsezYzoBtI'
    and c.action in ('dismissed', 'fixed')
);

-- nl/carport/productinformatie  [casing]
--   prod: Gumax® Glazen schuifwand
--   new : Gumax® glazen schuifwand
insert into overrides (editor, scope, action, store, page, finding_id, note)
select 'glossary-audit', 'finding', 'dismissed', 'nl', 'carport/productinformatie', 'qqTDIwIWUz5tapmI', 'Woordenlijst jan-2026: nieuwe site volgt de lijst (Gumax® glazen schuifwand); productie niet.'
where not exists (
  select 1 from overrides_current c
  where c.scope = 'finding' and c.finding_id = 'qqTDIwIWUz5tapmI'
    and c.action in ('dismissed', 'fixed')
);

-- nl/carport/productinformatie  [casing]
--   prod: Gumax® Steel look glazen schuifwand
--   new : Gumax® Steel Look glazen schuifwand
insert into overrides (editor, scope, action, store, page, finding_id, note)
select 'glossary-audit', 'finding', 'dismissed', 'nl', 'carport/productinformatie', 'KE6BlMQnkCa2Ioh5', 'Woordenlijst jan-2026: nieuwe site volgt de lijst (Gumax® Steel Look glazen schuifwand); productie niet.'
where not exists (
  select 1 from overrides_current c
  where c.scope = 'finding' and c.finding_id = 'KE6BlMQnkCa2Ioh5'
    and c.action in ('dismissed', 'fixed')
);

-- nl/carport/productinformatie  [casing]
--   prod: Gumax® Shading panel
--   new : Gumax® Shading Panel
insert into overrides (editor, scope, action, store, page, finding_id, note)
select 'glossary-audit', 'finding', 'dismissed', 'nl', 'carport/productinformatie', 'GT1PlIKxJ_ml6qth', 'Woordenlijst jan-2026: nieuwe site volgt de lijst (Gumax® Shading Panel(s)); productie niet.'
where not exists (
  select 1 from overrides_current c
  where c.scope = 'finding' and c.finding_id = 'GT1PlIKxJ_ml6qth'
    and c.action in ('dismissed', 'fixed')
);

-- nl/schuifwand  [casing]
--   prod: Gumax® Schuifwanden voor uw overkapping
--   new : Gumax® schuifwanden voor uw overkapping
insert into overrides (editor, scope, action, store, page, finding_id, note)
select 'glossary-audit', 'finding', 'dismissed', 'nl', 'schuifwand', 'OLxt2hGxMeImFanV', 'Woordenlijst jan-2026: nieuwe site volgt de lijst (Gumax® schuifwand(en)); productie niet.'
where not exists (
  select 1 from overrides_current c
  where c.scope = 'finding' and c.finding_id = 'OLxt2hGxMeImFanV'
    and c.action in ('dismissed', 'fixed')
);

-- nl/schuifwand  [casing]
--   prod: Gumax® Hor schuifdeur
--   new : Gumax® hor schuifdeur
insert into overrides (editor, scope, action, store, page, finding_id, note)
select 'glossary-audit', 'finding', 'dismissed', 'nl', 'schuifwand', 'BfqjkGgAgguVqflK', 'Woordenlijst jan-2026: nieuwe site volgt de lijst (Gumax® hor schuifdeur); productie niet.'
where not exists (
  select 1 from overrides_current c
  where c.scope = 'finding' and c.finding_id = 'BfqjkGgAgguVqflK'
    and c.action in ('dismissed', 'fixed')
);

-- nl/voordelen-van-een-aluminium-terrasoverkapping  [casing]
--   prod: Modern, klassiek, Tijdloos, Authentiek of Eigentijds ontwerp
--   new : Modern, Klassiek, Tijdloos, Authentiek of Eigentijds ontwerp
insert into overrides (editor, scope, action, store, page, finding_id, note)
select 'glossary-audit', 'finding', 'dismissed', 'nl', 'voordelen-van-een-aluminium-terrasoverkapping', 'kOL-7D7rmIAXlNwf', 'Woordenlijst jan-2026: nieuwe site volgt de lijst (Klassiek); productie niet.'
where not exists (
  select 1 from overrides_current c
  where c.scope = 'finding' and c.finding_id = 'kOL-7D7rmIAXlNwf'
    and c.action in ('dismissed', 'fixed')
);

-- nl/zwarte-overkapping  [casing]
--   prod: Stijlvol & tijdloos
--   new : Stijlvol & Tijdloos
insert into overrides (editor, scope, action, store, page, finding_id, note)
select 'glossary-audit', 'finding', 'dismissed', 'nl', 'zwarte-overkapping', 'xE43KjpKYf5Zhq0I', 'Woordenlijst jan-2026: nieuwe site volgt de lijst (Tijdloos); productie niet.'
where not exists (
  select 1 from overrides_current c
  where c.scope = 'finding' and c.finding_id = 'xE43KjpKYf5Zhq0I'
    and c.action in ('dismissed', 'fixed')
);

-- nl/zwarte-overkapping  [casing]
--   prod: glazen schuifwanden
--   new : Glazen schuifwanden
insert into overrides (editor, scope, action, store, page, finding_id, note)
select 'glossary-audit', 'finding', 'dismissed', 'nl', 'zwarte-overkapping', '2R0rqbue49DD7U7T', 'Woordenlijst jan-2026: nieuwe site volgt de lijst (Glazen schuifwand); productie niet.'
where not exists (
  select 1 from overrides_current c
  where c.scope = 'finding' and c.finding_id = '2R0rqbue49DD7U7T'
    and c.action in ('dismissed', 'fixed')
);

-- uk/(uk)glass-sliding-door/assembly  [casing]
--   prod: Dimensions glass sliding doors
--   new : Dimensions Glass sliding doors
insert into overrides (editor, scope, action, store, page, finding_id, note)
select 'glossary-audit', 'finding', 'dismissed', 'uk', '(uk)glass-sliding-door/assembly', '3pDtDCqQnUmhabwF', 'Woordenlijst jan-2026: nieuwe site volgt de lijst (Glass sliding doors); productie niet.'
where not exists (
  select 1 from overrides_current c
  where c.scope = 'finding' and c.finding_id = '3pDtDCqQnUmhabwF'
    and c.action in ('dismissed', 'fixed')
);

-- uk/(uk)sliding-door  [casing]
--   prod: Gumax® Sliding doors for your veranda
--   new : Gumax® sliding doors for your veranda
insert into overrides (editor, scope, action, store, page, finding_id, note)
select 'glossary-audit', 'finding', 'dismissed', 'uk', '(uk)sliding-door', 'L2nrLXe7FWkUhqC1', 'Woordenlijst jan-2026: nieuwe site volgt de lijst (Gumax® sliding doors); productie niet.'
where not exists (
  select 1 from overrides_current c
  where c.scope = 'finding' and c.finding_id = 'L2nrLXe7FWkUhqC1'
    and c.action in ('dismissed', 'fixed')
);

-- uk/(uk)sliding-door  [casing]
--   prod: Can be combined with Gumax® Shading panel & Steel Look
--   new : Can be combined with Gumax® Shading Panel & Steel Look
insert into overrides (editor, scope, action, store, page, finding_id, note)
select 'glossary-audit', 'finding', 'dismissed', 'uk', '(uk)sliding-door', 'x-2nL93YPTIDIAji', 'Woordenlijst jan-2026: nieuwe site volgt de lijst (Gumax® Shading Panel(s)); productie niet.'
where not exists (
  select 1 from overrides_current c
  where c.scope = 'finding' and c.finding_id = 'x-2nL93YPTIDIAji'
    and c.action in ('dismissed', 'fixed')
);

commit;
