"""Turn the audit's settled verdicts into a report and one idempotent SQL file.

Only the `settled` tier reaches SQL, and only the half of it where the NEW site is
the glossary-correct one. That asymmetry is the point:

  new correct        -> a dismissal. "These two exact strings are acceptable" is
                       exactly what the row says: the new site follows the word
                       list and production does not, so nothing is being asked.
  production correct -> nothing is written. The new site is wrong, which is copy
                        work in the CMS. `fixed` is a claim of fact ("I corrected
                        this") and writing it here would be a lie the re-check
                        would catch.

The insert is guarded on `overrides_current`, so re-running it cannot double-write
and cannot overrule a decision an editor has already made about the same finding.
"""

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
EDITOR = "glossary-audit"


def sq(s):
    return "'" + s.replace("'", "''") + "'"


def main():
    with open(os.path.join(HERE, "verdicts.json"), encoding="utf-8") as fh:
        rows = json.load(fh)

    settled = [r for r in rows if r["tier"] == "settled"]
    to_dismiss = [r for r in settled if r["verdict"] == "new"]
    to_fix = [r for r in settled if r["verdict"] == "production"]
    review = [
        r
        for r in rows
        if r["tier"] == "review" and r["verdict"] != "out-of-scope"
    ]

    # ---- SQL -------------------------------------------------------------
    out = [
        "-- Glossary audit: dismiss the differences where the NEW site already",
        "-- follows the January 2026 word list and production does not.",
        "--",
        "-- Generated by .scratch/glossary-audit/emit.py. Re-runnable: each row is",
        "-- guarded on overrides_current, so a finding an editor has already decided",
        "-- is left alone and a second run writes nothing.",
        "--",
        f"-- {len(to_dismiss)} findings. Every one is a case/punctuation-only difference",
        "-- on a short label, verified word-identical apart from case and the (R) mark.",
        "",
        "begin;",
        "",
    ]
    for r in to_dismiss:
        terms = ", ".join(sorted({e["term"] for e in r["evidence"]}))
        note = f"Woordenlijst jan-2026: nieuwe site volgt de lijst ({terms}); productie niet."
        out += [
            f"-- {r['store']}/{r['page']}  [{r['class']}]",
            f"--   prod: {r['prod']}",
            f"--   new : {r['new']}",
            "insert into overrides (editor, scope, action, store, page, finding_id, note)",
            "select {}, 'finding', 'dismissed', {}, {}, {}, {}".format(
                sq(EDITOR), sq(r["store"]), sq(r["page"]), sq(r["id"]), sq(note)
            ),
            "where not exists (",
            "  select 1 from overrides_current c",
            f"  where c.scope = 'finding' and c.finding_id = {sq(r['id'])}",
            "    and c.action in ('dismissed', 'fixed')",
            ");",
            "",
        ]
    out += ["commit;", ""]
    with open(os.path.join(HERE, "dismiss-new-correct.sql"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(out))

    # ---- report ----------------------------------------------------------
    md = [
        "# Glossary audit - Copy and Case or punctuation",
        "",
        "Every `copy`, `casing` and `meta-casing` finding on the "
        "`2026-08-19T15:15:18.599Z-135ccd35` snapshot, judged against "
        "*Woordenlijst Tuinmaximaal januari 2026*.",
        "",
        f"- **1,432** findings in scope (1,169 Copy + 259 Case or punctuation + 4 head casing)",
        f"- **{len(settled)}** settled by the word list -- word-identical, differing only in "
        "case, punctuation or the (R) mark",
        f"- **{len(to_dismiss)}** the new site gets right -> bulk dismissal "
        "(`dismiss-new-correct.sql`)",
        f"- **{len(to_fix)}** production gets right -> copy fixes for the CMS, no SQL",
        f"- **{len(review)}** the word list touches but cannot settle -> human review",
        "- the rest are outside the word list: rewrites, prices, and prose the "
        "glossary has no opinion on",
        "",
        "## The new site is correct - dismiss these",
        "",
        "| store | page | prod | new | term |",
        "| --- | --- | --- | --- | --- |",
    ]

    def cell(s):
        return s.replace("|", "\\|")

    for r in sorted(to_dismiss, key=lambda x: (x["store"], x["page"])):
        terms = ", ".join(sorted({e["term"] for e in r["evidence"]}))
        md.append(
            f"| {r['store']} | {cell(r['page'])} | {cell(r['prod'])} | "
            f"{cell(r['new'])} | {cell(terms)} |"
        )

    md += [
        "",
        "## Production is correct - fix the new site",
        "",
        "No SQL. A `fixed` event is a claim that someone corrected the page, and "
        "nobody has yet.",
        "",
        "| store | page | prod (correct) | new (wrong) | term |",
        "| --- | --- | --- | --- | --- |",
    ]
    for r in sorted(to_fix, key=lambda x: (x["store"], x["page"])):
        terms = ", ".join(sorted({e["term"] for e in r["evidence"]}))
        md.append(
            f"| {r['store']} | {cell(r['page'])} | {cell(r['prod'])} | "
            f"{cell(r['new'])} | {cell(terms)} |"
        )

    md += [
        "",
        "## Neither side is correct",
        "",
        "Both sides write the brand bare. The word list says `Gumax(R)`.",
        "",
        "| store | page | prod | new |",
        "| --- | --- | --- | --- |",
    ]
    seen = set()
    for r in sorted(rows, key=lambda x: (x["store"], x["page"])):
        if r["verdict"] != "neither":
            continue
        key = (r["store"], r["prod"], r["new"])
        if key in seen:
            continue
        seen.add(key)
        md.append(
            f"| {r['store']} | {cell(r['page'])} | {cell(r['prod'][:90])} | "
            f"{cell(r['new'][:90])} |"
        )

    md += [
        "",
        "## Touched but not settled - needs a human",
        "",
        "A glossary term moved, but the words changed too, so the difference is an "
        "editing decision and not a spelling one. `both-valid` means the list holds "
        "both names (`Shading Panel` and `Gumax(R) Shading Panel`) and licenses either.",
        "",
        "| store | verdict | prod | new |",
        "| --- | --- | --- | --- |",
    ]
    seen = set()
    for r in sorted(review, key=lambda x: (x["verdict"], x["store"])):
        key = (r["store"], r["prod"], r["new"])
        if key in seen:
            continue
        seen.add(key)
        md.append(
            f"| {r['store']} | {r['verdict']} | {cell(r['prod'][:90])} | "
            f"{cell(r['new'][:90])} |"
        )

    with open(os.path.join(HERE, "REPORT.md"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(md) + "\n")

    print("dismiss:", len(to_dismiss), " fix-list:", len(to_fix), " review:", len(review))


if __name__ == "__main__":
    main()
